### ISSUE TITLE
Issue with stan?

### ISSUE THREAD

**Issue by maxgarman** [usnistgov/AusteniteCalculator#32]
I am running into an issue with the stan file functionality that was implemented recently. Im not sure if its an issue on my end specifically or something happening overall. I've put the traceback below.

File "/Users/maxgarman/AusteniteCalculator/app/app.py", line 670, in update_output
stan_fit, unique_phases = compute_uncertainties.run_stan(results_table)
File "/Users/maxgarman/AusteniteCalculator/app/compute_uncertainties.py", line 160, in run_stan
iter_sampling=2000)
File "/Users/maxgarman/opt/anaconda3/envs/gsas-AustCalc/lib/python3.7/site-packages/cmdstanpy/model.py", line 1188, in sample
raise RuntimeError(msg)
RuntimeError: Error during sampling:

Command and output files:
RunSet: chains=4, chain_ids=[1, 2, 3, 4], num_processes=4
cmd (chain 1):
['/Users/maxgarman/AusteniteCalculator/stan_files/one_sample.exe', 'id=1', 'random', 'seed=79443', 'data', 'file=/var/folders/00/j86sgdl14j58ndx3twspz9600000gn/T/tmpqcl92vep/55mivgaw.json', 'output', 'file=/var/folders/00/j86sgdl14j58ndx3twspz9600000gn/T/tmpqcl92vep/one_sample8zfhqnda/one_sample-20220726120059_1.csv', 'method=sample', 'num_samples=2000', 'num_warmup=2000', 'algorithm=hmc', 'adapt', 'engaged=1']
retcodes=[-1, -1, -1, -1]
per-chain output files (showing chain 1 only):
csv_file:
/var/folders/00/j86sgdl14j58ndx3twspz9600000gn/T/tmpqcl92vep/one_sample8zfhqnda/one_sample-20220726120059_1.csv
console_msgs (if any):
/var/folders/00/j86sgdl14j58ndx3twspz9600000gn/T/tmpqcl92vep/one_sample8zfhqnda/one_sample-20220726120059_0-stdout.txt
Consider re-running with show_console=True if the above output is unclear!

**Comment by creuzige** [comment]
Added note to README about this
