### ISSUE TITLE
JSON file not linking properly

### ISSUE THREAD

**Issue by mrcox5** [usnistgov/AusteniteCalculator#51]
When attempting to run the "begin analysis" item on the app, the example options (Example05) seems to run fine. When manually selecting a .json file however (using the "Crystallites Illuminated JSON..." button, the following error is output, even when using the same(?) .json file  "File: Example05.json" from the example data folder:

Traceback (most recent call last):
  File "C:\Users\mrc5\Documents\AusteniteCalculator\AusteniteCalculator-master\app\app.py", line 942, in update_output
    json_fname)
  File "C:\Users\mrc5\Documents\AusteniteCalculator\AusteniteCalculator-master\app\compute_results.py", line 1445, in process_data_input
    json_fname)
TypeError: cannot unpack non-iterable NoneType object

**Comment by creuzige** [comment]
I think when we tested the new app.py, we may not have used the upload buttons.  I'm guessing something in the app.py file is not linking as expected...

**Comment by creuzige** [comment]
Fixed in [b58e7b0](https://github.com/usnistgov/AusteniteCalculator/commit/b58e7b05d640b1d1324c3ebb8c31dc457aaa6885), was missing a return in the manual addition of files.
